-- Постоянные награды чемпионата → история карьеры игрока и клуба
-- XP/уровни сезона обнуляются с новым сезоном; эти записи остаются навсегда.

create table if not exists public.championship_career_awards (
  id bigint generated by default as identity primary key,
  championship_id bigint not null
    references public.championships (id) on delete cascade,
  season text not null,
  award_key text not null unique,
  award_code text not null,
  award_title text not null,
  icon text not null default '🏅',
  player_id bigint references public.players (id) on delete cascade,
  team_id bigint references public.championship_teams (id) on delete set null,
  scope text not null default 'player'
    check (scope in ('player', 'club')),
  awarded_at timestamptz not null default now()
);

create index if not exists championship_career_awards_player_idx
  on public.championship_career_awards (player_id, awarded_at desc);

create index if not exists championship_career_awards_club_idx
  on public.championship_career_awards (scope, season);

alter table public.championship_career_awards enable row level security;

drop policy if exists "championship_career_awards_select" on public.championship_career_awards;
create policy "championship_career_awards_select"
  on public.championship_career_awards for select to anon, authenticated using (true);
drop policy if exists "championship_career_awards_write" on public.championship_career_awards;
create policy "championship_career_awards_write"
  on public.championship_career_awards for all to authenticated using (true) with check (true);
