-- Мифическая карточка «Чёрное Золото» + сборная тура + красные карточки
-- Supabase → SQL Editor → Run после championship.sql и championship_progress.sql

-- Красные в статистике матча чемпионата
alter table public.championship_match_player_stats
  add column if not exists red_cards integer not null default 0;

-- Символическая сборная тура / элита матча
create table if not exists public.championship_tour_xi (
  id bigint generated by default as identity primary key,
  championship_id bigint not null
    references public.championships (id) on delete cascade,
  round_id bigint
    references public.championship_rounds (id) on delete cascade,
  match_id bigint
    references public.championship_matches (id) on delete cascade,
  player_id bigint not null
    references public.players (id) on delete cascade,
  slot integer not null default 1,
  match_rating numeric(4, 1),
  source text not null default 'tour'
    check (source in ('tour', 'match_elite')),
  created_at timestamptz not null default now()
);

create index if not exists championship_tour_xi_champ_player_idx
  on public.championship_tour_xi (championship_id, player_id);

create index if not exists championship_tour_xi_round_idx
  on public.championship_tour_xi (round_id)
  where round_id is not null;

create index if not exists championship_tour_xi_match_idx
  on public.championship_tour_xi (match_id)
  where match_id is not null;

-- Одна карточка каждого кода на игрока в сезоне
create unique index if not exists championship_season_cards_code_uniq
  on public.championship_season_cards (championship_id, player_id, card_code);

alter table public.championship_tour_xi enable row level security;

drop policy if exists "championship_tour_xi_select" on public.championship_tour_xi;
create policy "championship_tour_xi_select"
  on public.championship_tour_xi for select to anon, authenticated using (true);
drop policy if exists "championship_tour_xi_write" on public.championship_tour_xi;
create policy "championship_tour_xi_write"
  on public.championship_tour_xi for all to authenticated using (true) with check (true);
