-- Чемпионат: отдельный сезон, отдельные сущности, без смешивания с карьерой.
-- Supabase → SQL Editor → Run

-- 1) Сезоны чемпионата
create table if not exists public.championships (
  id bigint generated by default as identity primary key,
  name text not null,
  season text not null,
  starts_at date,
  ends_at date,
  status text not null default 'active'
    check (status in ('draft', 'active', 'finished')),
  created_at timestamptz not null default now()
);

create unique index if not exists championships_season_uidx
  on public.championships (season);

-- 2) Команды (переиспользуются между сезонами)
create table if not exists public.championship_teams (
  id bigint generated by default as identity primary key,
  name text not null,
  logo_url text,
  primary_color text not null default '#fbbf24',
  secondary_color text not null default '#78350f',
  created_at timestamptz not null default now(),
  unique (name)
);

-- 3) Участники сезона
create table if not exists public.championship_participants (
  championship_id bigint not null
    references public.championships (id) on delete cascade,
  team_id bigint not null
    references public.championship_teams (id) on delete cascade,
  primary key (championship_id, team_id)
);

-- 4) Матчи чемпионата (не таблица matches клуба)
create table if not exists public.championship_matches (
  id bigint generated by default as identity primary key,
  championship_id bigint not null
    references public.championships (id) on delete cascade,
  home_team_id bigint not null
    references public.championship_teams (id),
  away_team_id bigint not null
    references public.championship_teams (id),
  match_date date not null,
  match_time text not null default '18:00',
  location text not null default '',
  home_goals integer,
  away_goals integer,
  is_played boolean not null default false,
  is_live boolean not null default false,
  created_at timestamptz not null default now(),
  check (home_team_id <> away_team_id)
);

create index if not exists championship_matches_champ_idx
  on public.championship_matches (championship_id, match_date desc, id desc);

-- 5) События матча чемпионата (голы/пассы/MVP сезона)
create table if not exists public.championship_match_player_stats (
  id bigint generated by default as identity primary key,
  match_id bigint not null
    references public.championship_matches (id) on delete cascade,
  player_id bigint not null
    references public.players (id) on delete cascade,
  team_id bigint not null
    references public.championship_teams (id),
  goals integer not null default 0,
  assists integer not null default 0,
  is_mvp boolean not null default false,
  match_rating numeric(4, 1),
  unique (match_id, player_id)
);

create index if not exists championship_match_player_stats_player_idx
  on public.championship_match_player_stats (player_id);

-- 6) Сезонная статистика игрока (обнуляется с новым чемпионатом)
create table if not exists public.championship_player_season_stats (
  id bigint generated by default as identity primary key,
  championship_id bigint not null
    references public.championships (id) on delete cascade,
  player_id bigint not null
    references public.players (id) on delete cascade,
  team_id bigint not null
    references public.championship_teams (id),
  matches_played integer not null default 0,
  goals integer not null default 0,
  assists integer not null default 0,
  mvp_count integer not null default 0,
  rating_sum numeric(10, 2) not null default 0,
  rating_count integer not null default 0,
  unique (championship_id, player_id)
);

create index if not exists championship_player_season_stats_champ_idx
  on public.championship_player_season_stats (championship_id);

-- RLS
alter table public.championships enable row level security;
alter table public.championship_teams enable row level security;
alter table public.championship_participants enable row level security;
alter table public.championship_matches enable row level security;
alter table public.championship_match_player_stats enable row level security;
alter table public.championship_player_season_stats enable row level security;

drop policy if exists "championships_select" on public.championships;
create policy "championships_select"
  on public.championships for select to anon, authenticated using (true);
drop policy if exists "championships_write" on public.championships;
create policy "championships_write"
  on public.championships for all to authenticated using (true) with check (true);

drop policy if exists "championship_teams_select" on public.championship_teams;
create policy "championship_teams_select"
  on public.championship_teams for select to anon, authenticated using (true);
drop policy if exists "championship_teams_write" on public.championship_teams;
create policy "championship_teams_write"
  on public.championship_teams for all to authenticated using (true) with check (true);

drop policy if exists "championship_participants_select" on public.championship_participants;
create policy "championship_participants_select"
  on public.championship_participants for select to anon, authenticated using (true);
drop policy if exists "championship_participants_write" on public.championship_participants;
create policy "championship_participants_write"
  on public.championship_participants for all to authenticated using (true) with check (true);

drop policy if exists "championship_matches_select" on public.championship_matches;
create policy "championship_matches_select"
  on public.championship_matches for select to anon, authenticated using (true);
drop policy if exists "championship_matches_write" on public.championship_matches;
create policy "championship_matches_write"
  on public.championship_matches for all to authenticated using (true) with check (true);

drop policy if exists "championship_match_player_stats_select" on public.championship_match_player_stats;
create policy "championship_match_player_stats_select"
  on public.championship_match_player_stats for select to anon, authenticated using (true);
drop policy if exists "championship_match_player_stats_write" on public.championship_match_player_stats;
create policy "championship_match_player_stats_write"
  on public.championship_match_player_stats for all to authenticated using (true) with check (true);

drop policy if exists "championship_player_season_stats_select" on public.championship_player_season_stats;
create policy "championship_player_season_stats_select"
  on public.championship_player_season_stats for select to anon, authenticated using (true);
drop policy if exists "championship_player_season_stats_write" on public.championship_player_season_stats;
create policy "championship_player_season_stats_write"
  on public.championship_player_season_stats for all to authenticated using (true) with check (true);

-- Инициализация сезонной статистики всех игроков клуба (нули)
create or replace function public.init_championship_season_stats(
  p_championship_id bigint,
  p_home_team_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.championship_player_season_stats (
    championship_id, player_id, team_id,
    matches_played, goals, assists, mvp_count, rating_sum, rating_count
  )
  select
    p_championship_id,
    p.id,
    p_home_team_id,
    0, 0, 0, 0, 0, 0
  from public.players p
  on conflict (championship_id, player_id) do nothing;
end;
$$;

-- Сид первого сезона (идемпотентно)
insert into public.championship_teams (name, primary_color, secondary_color)
values
  ('Дженгутай', '#fbbf24', '#78350f'),
  ('Доргели', '#38bdf8', '#0c4a6e'),
  ('Бирлик (Доргели)', '#a78bfa', '#4c1d95'),
  ('Какашура', '#34d399', '#064e3b'),
  ('Казанище', '#f472b6', '#831843'),
  ('Какашура 2', '#fb7185', '#7f1d1d')
on conflict (name) do nothing;

insert into public.championships (name, season, starts_at, status)
select 'ДоргеЛига', '2026', current_date, 'active'
where not exists (
  select 1 from public.championships where season = '2026'
);

update public.championships
set name = 'ДоргеЛига'
where season = '2026';

insert into public.championship_participants (championship_id, team_id)
select c.id, t.id
from public.championships c
cross join public.championship_teams t
where c.season = '2026'
  and t.name in (
    'Дженгутай',
    'Доргели',
    'Бирлик (Доргели)',
    'Какашура',
    'Казанище',
    'Какашура 2'
  )
on conflict do nothing;

do $$
declare
  v_champ_id bigint;
  v_home_id bigint;
begin
  select id into v_champ_id from public.championships where season = '2026' limit 1;
  select id into v_home_id from public.championship_teams where name = 'Дженгутай' limit 1;
  if v_champ_id is not null and v_home_id is not null then
    perform public.init_championship_season_stats(v_champ_id, v_home_id);
  end if;
end $$;
