-- Прогресс сезона чемпионата (отдельно от карьеры)
-- Supabase → SQL Editor → Run после championship.sql

-- Туры сезона
create table if not exists public.championship_rounds (
  id bigint generated by default as identity primary key,
  championship_id bigint not null
    references public.championships (id) on delete cascade,
  round_number integer not null,
  title text,
  status text not null default 'upcoming'
    check (status in ('upcoming', 'active', 'finished')),
  results_applied_at timestamptz,
  created_at timestamptz not null default now(),
  unique (championship_id, round_number)
);

create index if not exists championship_rounds_champ_idx
  on public.championship_rounds (championship_id, round_number);

-- Привязка матча к туру
alter table public.championship_matches
  add column if not exists round_id bigint
    references public.championship_rounds (id) on delete set null;

alter table public.championship_matches
  add column if not exists tour_results_applied boolean not null default false;

-- Прогресс игрока в чемпионате (сбрасывается с новым сезоном — новая строка на championship_id)
create table if not exists public.championship_player_progress (
  id bigint generated by default as identity primary key,
  championship_id bigint not null
    references public.championships (id) on delete cascade,
  player_id bigint not null
    references public.players (id) on delete cascade,
  team_id bigint not null
    references public.championship_teams (id),
  season_xp integer not null default 0,
  season_level integer not null default 1,
  season_rating numeric(4, 1) not null default 0,
  season_cards integer not null default 0,
  season_rewards integer not null default 0,
  rating_sum numeric(10, 2) not null default 0,
  rating_count integer not null default 0,
  updated_at timestamptz not null default now(),
  unique (championship_id, player_id)
);

create index if not exists championship_player_progress_champ_idx
  on public.championship_player_progress (championship_id, season_xp desc);

-- Карточки сезона (архитектура; содержимое позже)
create table if not exists public.championship_season_cards (
  id bigint generated by default as identity primary key,
  championship_id bigint not null
    references public.championships (id) on delete cascade,
  player_id bigint not null
    references public.players (id) on delete cascade,
  card_code text not null,
  card_title text not null default '',
  rarity text not null default 'common',
  earned_at timestamptz not null default now(),
  meta jsonb not null default '{}'::jsonb
);

create index if not exists championship_season_cards_player_idx
  on public.championship_season_cards (championship_id, player_id);

-- Награды сезона (архитектура; содержимое позже)
create table if not exists public.championship_season_rewards (
  id bigint generated by default as identity primary key,
  championship_id bigint not null
    references public.championships (id) on delete cascade,
  player_id bigint
    references public.players (id) on delete set null,
  team_id bigint
    references public.championship_teams (id) on delete set null,
  reward_code text not null,
  reward_title text not null default '',
  earned_at timestamptz not null default now(),
  meta jsonb not null default '{}'::jsonb
);

create index if not exists championship_season_rewards_champ_idx
  on public.championship_season_rewards (championship_id);

-- Лог начисления XP за матч (идемпотентность итогов тура)
create table if not exists public.championship_match_xp_log (
  id bigint generated by default as identity primary key,
  match_id bigint not null
    references public.championship_matches (id) on delete cascade,
  player_id bigint not null
    references public.players (id) on delete cascade,
  match_rating numeric(4, 1),
  xp_gained integer not null default 0,
  level_before integer not null default 1,
  level_after integer not null default 1,
  created_at timestamptz not null default now(),
  unique (match_id, player_id)
);

-- RLS
alter table public.championship_rounds enable row level security;
alter table public.championship_player_progress enable row level security;
alter table public.championship_season_cards enable row level security;
alter table public.championship_season_rewards enable row level security;
alter table public.championship_match_xp_log enable row level security;

drop policy if exists "championship_rounds_select" on public.championship_rounds;
create policy "championship_rounds_select"
  on public.championship_rounds for select to anon, authenticated using (true);
drop policy if exists "championship_rounds_write" on public.championship_rounds;
create policy "championship_rounds_write"
  on public.championship_rounds for all to authenticated using (true) with check (true);

drop policy if exists "championship_player_progress_select" on public.championship_player_progress;
create policy "championship_player_progress_select"
  on public.championship_player_progress for select to anon, authenticated using (true);
drop policy if exists "championship_player_progress_write" on public.championship_player_progress;
create policy "championship_player_progress_write"
  on public.championship_player_progress for all to authenticated using (true) with check (true);

drop policy if exists "championship_season_cards_select" on public.championship_season_cards;
create policy "championship_season_cards_select"
  on public.championship_season_cards for select to anon, authenticated using (true);
drop policy if exists "championship_season_cards_write" on public.championship_season_cards;
create policy "championship_season_cards_write"
  on public.championship_season_cards for all to authenticated using (true) with check (true);

drop policy if exists "championship_season_rewards_select" on public.championship_season_rewards;
create policy "championship_season_rewards_select"
  on public.championship_season_rewards for select to anon, authenticated using (true);
drop policy if exists "championship_season_rewards_write" on public.championship_season_rewards;
create policy "championship_season_rewards_write"
  on public.championship_season_rewards for all to authenticated using (true) with check (true);

drop policy if exists "championship_match_xp_log_select" on public.championship_match_xp_log;
create policy "championship_match_xp_log_select"
  on public.championship_match_xp_log for select to anon, authenticated using (true);
drop policy if exists "championship_match_xp_log_write" on public.championship_match_xp_log;
create policy "championship_match_xp_log_write"
  on public.championship_match_xp_log for all to authenticated using (true) with check (true);

-- Инициализация прогресса всех игроков клуба на новый сезон
create or replace function public.init_championship_player_progress(
  p_championship_id bigint,
  p_home_team_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.championship_player_progress (
    championship_id, player_id, team_id,
    season_xp, season_level, season_rating,
    season_cards, season_rewards, rating_sum, rating_count
  )
  select
    p_championship_id,
    p.id,
    p_home_team_id,
    0, 1, 0,
    0, 0, 0, 0
  from public.players p
  on conflict (championship_id, player_id) do nothing;
end;
$$;

-- Расширяем init статистики: также прогресс
create or replace function public.init_championship_season_stats(
  p_championship_id bigint,
  p_home_team_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.championship_player_season_stats (
    championship_id, player_id, team_id,
    matches_played, goals, assists, mvp_count, rating_sum, rating_count
  )
  select
    p_championship_id,
    p.id,
    p_home_team_id,
    0, 0, 0, 0, 0, 0
  from public.players p
  on conflict (championship_id, player_id) do nothing;

  perform public.init_championship_player_progress(p_championship_id, p_home_team_id);
end;
$$;

-- Инициализация для активного сезона
do $$
declare
  v_champ_id bigint;
  v_home_id bigint;
begin
  select id into v_champ_id
  from public.championships
  where status = 'active'
  order by id desc
  limit 1;
  select id into v_home_id
  from public.championship_teams
  where name = 'Дженгутай'
  limit 1;
  if v_champ_id is not null and v_home_id is not null then
    perform public.init_championship_player_progress(v_champ_id, v_home_id);
  end if;
end $$;
