-- Оценки от зрителей (без входа в аккаунт) — отдельно от оценок игроков.
-- Не влияет на match_player_rating_summary / players.rating.
-- Выполните в Supabase → SQL Editor.

create table if not exists match_guest_rating_votes (
  id bigint generated by default as identity primary key,
  match_id bigint not null references matches(id) on delete cascade,
  guest_token text not null,
  guest_name text,
  rated_player_id bigint not null references players(id) on delete cascade,
  stars integer not null check (stars >= 1 and stars <= 10),
  created_at timestamptz default now(),
  unique (match_id, guest_token, rated_player_id)
);

create index if not exists match_guest_rating_votes_match_id_idx
  on match_guest_rating_votes (match_id);

create index if not exists match_guest_rating_votes_guest_token_idx
  on match_guest_rating_votes (match_id, guest_token);

alter table match_guest_rating_votes enable row level security;

-- Читать может кто угодно (показываем среднюю оценку зрителей всем)
create policy "match_guest_rating_votes_select"
  on match_guest_rating_votes for select
  to anon, authenticated
  using (true);

-- Вставлять может кто угодно без входа — это и есть смысл гостевого голосования.
-- guest_token генерируется в браузере и хранится в localStorage зрителя.
create policy "match_guest_rating_votes_insert"
  on match_guest_rating_votes for insert
  to anon, authenticated
  with check (
    length(guest_token) >= 16
    and stars >= 1 and stars <= 10
  );

-- Гость может поменять свою же оценку (по тому же guest_token), но не чужую.
create policy "match_guest_rating_votes_update"
  on match_guest_rating_votes for update
  to anon, authenticated
  using (true)
  with check (
    length(guest_token) >= 16
    and stars >= 1 and stars <= 10
  );

-- Удаление отключено намеренно (нет policy для delete) — гость не может стереть голос,
-- админ при необходимости чистит через service role.
