-- MVP-голосование после матча (отдельно от match_player_rating_votes).
-- Supabase → SQL Editor → Run

-- Сессия голосования на конкретный match_id
create table if not exists public.match_voting_sessions (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  status text not null default 'open' check (status in ('open', 'closed')),
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  unique (match_id)
);

create index if not exists match_voting_sessions_match_id_idx
  on public.match_voting_sessions (match_id);

create index if not exists match_voting_sessions_status_idx
  on public.match_voting_sessions (status);

-- Один голос игрока за MVP конкретного матча
create table if not exists public.match_votes (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  voter_player_id bigint not null references public.players(id) on delete cascade,
  voted_player_id bigint not null references public.players(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (match_id, voter_player_id)
);

create index if not exists match_votes_match_id_idx
  on public.match_votes (match_id);

create index if not exists match_votes_voted_player_id_idx
  on public.match_votes (voted_player_id);

alter table public.match_voting_sessions enable row level security;
alter table public.match_votes enable row level security;

grant select on public.match_voting_sessions to anon, authenticated;
grant select, insert, update, delete on public.match_voting_sessions to authenticated;

grant select on public.match_votes to anon, authenticated;
grant select, insert on public.match_votes to authenticated;

drop policy if exists "match_voting_sessions_select" on public.match_voting_sessions;
create policy "match_voting_sessions_select"
  on public.match_voting_sessions for select to anon, authenticated using (true);

drop policy if exists "match_voting_sessions_admin_write" on public.match_voting_sessions;
create policy "match_voting_sessions_admin_write"
  on public.match_voting_sessions for all to authenticated
  using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  )
  with check (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

drop policy if exists "match_votes_select" on public.match_votes;
create policy "match_votes_select"
  on public.match_votes for select to anon, authenticated using (true);

drop policy if exists "match_votes_insert_own" on public.match_votes;
create policy "match_votes_insert_own"
  on public.match_votes for insert to authenticated
  with check (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.player_id = voter_player_id
    )
  );

-- Голоса не обновляем и не удаляем клиентом (один голос навсегда)
drop policy if exists "match_votes_no_update" on public.match_votes;
drop policy if exists "match_votes_no_delete" on public.match_votes;
