-- Оценки игроков после матча (1–10 звёзд).
-- Запустите в Supabase → SQL Editor после match_history.sql

create table if not exists match_player_rating_votes (
  id bigint generated by default as identity primary key,
  match_id bigint not null references matches(id) on delete cascade,
  voter_player_id bigint not null references players(id) on delete cascade,
  rated_player_id bigint not null references players(id) on delete cascade,
  stars integer not null check (stars >= 1 and stars <= 10),
  created_at timestamptz default now(),
  unique (match_id, voter_player_id, rated_player_id)
);

create index if not exists match_player_rating_votes_match_id_idx
  on match_player_rating_votes (match_id);

create table if not exists match_player_rating_summary (
  id bigint generated by default as identity primary key,
  match_id bigint not null references matches(id) on delete cascade,
  player_id bigint not null references players(id) on delete cascade,
  avg_stars numeric(4, 2) not null default 0,
  match_rating numeric(3, 1) not null default 0,
  vote_count integer not null default 0,
  is_mvp boolean not null default false,
  rating_before integer,
  rating_after integer,
  unique (match_id, player_id)
);

create index if not exists match_player_rating_summary_match_id_idx
  on match_player_rating_summary (match_id);

create index if not exists match_player_rating_summary_player_id_idx
  on match_player_rating_summary (player_id);

alter table match_player_rating_votes enable row level security;
alter table match_player_rating_summary enable row level security;

create policy "match_player_rating_votes_select"
  on match_player_rating_votes for select to anon, authenticated using (true);

create policy "match_player_rating_votes_insert"
  on match_player_rating_votes for insert to anon, authenticated with check (true);

create policy "match_player_rating_votes_update"
  on match_player_rating_votes for update to anon, authenticated using (true) with check (true);

create policy "match_player_rating_votes_delete"
  on match_player_rating_votes for delete to anon, authenticated using (true);

create policy "match_player_rating_summary_select"
  on match_player_rating_summary for select to anon, authenticated using (true);

create policy "match_player_rating_summary_insert"
  on match_player_rating_summary for insert to anon, authenticated with check (true);

create policy "match_player_rating_summary_update"
  on match_player_rating_summary for update to anon, authenticated using (true) with check (true);

create policy "match_player_rating_summary_delete"
  on match_player_rating_summary for delete to anon, authenticated using (true);
