-- Участие в матче: игрок сам нажимает «Не играл» в голосовании
-- (по умолчанию все считаются участниками, пока не отметятся)
-- Запустите в Supabase → SQL Editor, затем match_participation_rls.sql

create table if not exists public.match_player_participation (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  participated boolean not null default true,
  skipped_rating_vote boolean not null default false,
  unique (match_id, player_id)
);

create index if not exists match_player_participation_match_id_idx
  on public.match_player_participation (match_id);

alter table public.match_player_participation enable row level security;

grant select on public.match_player_participation to anon, authenticated;
grant select, insert, update, delete on public.match_player_participation to authenticated;

drop policy if exists "match_player_participation_select" on public.match_player_participation;
create policy "match_player_participation_select"
  on public.match_player_participation for select to anon, authenticated using (true);

-- Политики записи (только своя строка) — в match_participation_rls.sql
