-- Реакции игроков после матча (репутация команды).
-- Supabase → SQL Editor → Run

create table if not exists public.match_player_reactions (
  id bigint generated by default as identity primary key,
  match_id bigint not null
    references public.matches (id) on delete cascade,
  from_player_id bigint not null
    references public.players (id) on delete cascade,
  to_player_id bigint not null
    references public.players (id) on delete cascade,
  reaction_code text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (match_id, from_player_id, to_player_id),
  check (from_player_id <> to_player_id)
);

create index if not exists match_player_reactions_match_to_idx
  on public.match_player_reactions (match_id, to_player_id);

create index if not exists match_player_reactions_to_idx
  on public.match_player_reactions (to_player_id);

-- Накопленная репутация за всё время
create table if not exists public.player_reaction_totals (
  player_id bigint not null
    references public.players (id) on delete cascade,
  reaction_code text not null,
  count integer not null default 0 check (count >= 0),
  primary key (player_id, reaction_code)
);

alter table public.match_player_reactions enable row level security;
alter table public.player_reaction_totals enable row level security;

drop policy if exists "match_player_reactions_select" on public.match_player_reactions;
create policy "match_player_reactions_select"
  on public.match_player_reactions for select to anon, authenticated using (true);

drop policy if exists "match_player_reactions_insert" on public.match_player_reactions;
create policy "match_player_reactions_insert"
  on public.match_player_reactions for insert to authenticated
  with check (
    from_player_id = (
      select player_id from public.profiles where id = auth.uid() limit 1
    )
  );

drop policy if exists "match_player_reactions_update" on public.match_player_reactions;
create policy "match_player_reactions_update"
  on public.match_player_reactions for update to authenticated
  using (
    from_player_id = (
      select player_id from public.profiles where id = auth.uid() limit 1
    )
  )
  with check (
    from_player_id = (
      select player_id from public.profiles where id = auth.uid() limit 1
    )
  );

drop policy if exists "match_player_reactions_delete" on public.match_player_reactions;
create policy "match_player_reactions_delete"
  on public.match_player_reactions for delete to authenticated
  using (
    from_player_id = (
      select player_id from public.profiles where id = auth.uid() limit 1
    )
  );

drop policy if exists "player_reaction_totals_select" on public.player_reaction_totals;
create policy "player_reaction_totals_select"
  on public.player_reaction_totals for select to anon, authenticated using (true);

drop policy if exists "player_reaction_totals_write" on public.player_reaction_totals;
create policy "player_reaction_totals_write"
  on public.player_reaction_totals for all to authenticated
  using (true) with check (true);

grant select on public.match_player_reactions to anon, authenticated;
grant select, insert, update, delete on public.match_player_reactions to authenticated;
grant select on public.player_reaction_totals to anon, authenticated;
grant select, insert, update, delete on public.player_reaction_totals to authenticated;
