-- Запустите этот SQL в Supabase → SQL Editor

alter table matches
  add column if not exists ndfk_goals integer default 0,
  add column if not exists opponent_goals integer default 0,
  add column if not exists is_played boolean default false;

create table if not exists match_player_stats (
  id bigint generated by default as identity primary key,
  match_id bigint not null references matches(id) on delete cascade,
  player_id bigint not null references players(id) on delete cascade,
  goals integer not null default 0,
  assists integer not null default 0,
  unique (match_id, player_id)
);

create index if not exists match_player_stats_match_id_idx
  on match_player_stats (match_id);

create index if not exists match_player_stats_player_id_idx
  on match_player_stats (player_id);

-- Row Level Security (без этого будет ошибка при сохранении голов)
alter table match_player_stats enable row level security;

create policy "match_player_stats_select"
  on match_player_stats for select to anon, authenticated using (true);

create policy "match_player_stats_insert"
  on match_player_stats for insert to anon, authenticated with check (true);

create policy "match_player_stats_update"
  on match_player_stats for update to anon, authenticated using (true) with check (true);

create policy "match_player_stats_delete"
  on match_player_stats for delete to anon, authenticated using (true);
