-- Голосование готовности к матчу. Запустите в Supabase → SQL Editor

create table if not exists match_availability (
  id bigint generated by default as identity primary key,
  match_id bigint not null references matches(id) on delete cascade,
  player_id bigint not null references players(id) on delete cascade,
  status text not null check (status in ('ready', 'maybe', 'absent')),
  updated_at timestamptz default now(),
  unique (match_id, player_id)
);

create index if not exists match_availability_match_id_idx
  on match_availability (match_id);

alter table match_availability enable row level security;

create policy "match_availability_select"
  on match_availability for select to anon, authenticated using (true);

create policy "match_availability_insert"
  on match_availability for insert to anon, authenticated with check (true);

create policy "match_availability_update"
  on match_availability for update to anon, authenticated using (true) with check (true);

create policy "match_availability_delete"
  on match_availability for delete to anon, authenticated using (true);
