-- Post-match gamification: achievements, career progression (XP/level/title)
-- and season average ratings.
--
-- Run in Supabase → SQL Editor (hosted) after the match rating tables
-- (match_ratings.sql, match_history.sql, match_participation.sql).
-- All writes happen through the service role in the recalc pipeline; clients
-- only read. Safe to re-run (idempotent).

-- --------------------------------------------------------------------------
-- Achievements unlocked by a player (one row per earned achievement)
-- --------------------------------------------------------------------------
create table if not exists public.player_achievements (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  achievement_key text not null,
  match_id bigint references public.matches(id) on delete set null,
  earned_at timestamptz not null default now(),
  unique (player_id, achievement_key)
);

create index if not exists player_achievements_player_id_idx
  on public.player_achievements (player_id);

-- --------------------------------------------------------------------------
-- Career progression: cumulative XP, derived level and title
-- --------------------------------------------------------------------------
create table if not exists public.player_career (
  player_id bigint primary key references public.players(id) on delete cascade,
  xp integer not null default 0,
  level integer not null default 1,
  title text not null default 'Новичок',
  matches_rated integer not null default 0,
  updated_at timestamptz not null default now()
);

-- --------------------------------------------------------------------------
-- Season average rating (one row per player per season/year)
-- --------------------------------------------------------------------------
create table if not exists public.player_season_stats (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  season integer not null,
  matches_rated integer not null default 0,
  sum_rating numeric(8, 2) not null default 0,
  avg_rating numeric(4, 2) not null default 0,
  updated_at timestamptz not null default now(),
  unique (player_id, season)
);

create index if not exists player_season_stats_player_id_idx
  on public.player_season_stats (player_id);

-- --------------------------------------------------------------------------
-- RLS: public read, writes only via service role (recalc pipeline)
-- --------------------------------------------------------------------------
alter table public.player_achievements enable row level security;
alter table public.player_career enable row level security;
alter table public.player_season_stats enable row level security;

grant select on public.player_achievements,
  public.player_career, public.player_season_stats to anon, authenticated;

drop policy if exists player_achievements_select on public.player_achievements;
create policy player_achievements_select
  on public.player_achievements for select to anon, authenticated using (true);

drop policy if exists player_career_select on public.player_career;
create policy player_career_select
  on public.player_career for select to anon, authenticated using (true);

drop policy if exists player_season_stats_select on public.player_season_stats;
create policy player_season_stats_select
  on public.player_season_stats for select to anon, authenticated using (true);
