-- Универсальная система достижений игроков.
-- Запустите в Supabase → SQL Editor.

-- Опциональная расширенная статистика матча (пока 0, если не заполняют)
alter table match_player_stats
  add column if not exists tackles integer not null default 0;

alter table match_player_stats
  add column if not exists interceptions integer not null default 0;

-- Когда достижения по матчу уже прогнаны (после дедлайна голосования)
alter table matches
  add column if not exists achievements_synced_at timestamptz;

-- Полученные достижения
create table if not exists player_achievements (
  id bigint generated by default as identity primary key,
  player_id bigint not null references players(id) on delete cascade,
  achievement_id text not null,
  unlocked_at timestamptz not null default now(),
  xp_awarded integer not null default 0,
  unique (player_id, achievement_id)
);

create index if not exists player_achievements_player_id_idx
  on player_achievements (player_id);

create index if not exists player_achievements_unlocked_at_idx
  on player_achievements (unlocked_at desc);

-- Очередь для красивого тоста «Новое достижение»
create table if not exists player_achievement_events (
  id bigint generated by default as identity primary key,
  player_id bigint not null references players(id) on delete cascade,
  achievement_id text not null,
  xp_awarded integer not null default 0,
  created_at timestamptz not null default now(),
  seen_at timestamptz
);

create index if not exists player_achievement_events_unseen_idx
  on player_achievement_events (player_id, created_at desc)
  where seen_at is null;

alter table player_achievements enable row level security;
alter table player_achievement_events enable row level security;

drop policy if exists "player_achievements_select" on player_achievements;
create policy "player_achievements_select"
  on player_achievements for select to anon, authenticated using (true);

drop policy if exists "player_achievement_events_select" on player_achievement_events;
create policy "player_achievement_events_select"
  on player_achievement_events for select to anon, authenticated using (true);

drop policy if exists "player_achievement_events_update" on player_achievement_events;
create policy "player_achievement_events_update"
  on player_achievement_events for update to anon, authenticated using (true) with check (true);

-- Запись достижений — через service_role / admin client
grant select on player_achievements to anon, authenticated;
grant select, update on player_achievement_events to anon, authenticated;
