-- Эпизод «Рейтинг» — оценка характеристик команды
-- Supabase → SQL Editor → Run

create table if not exists public.rating_episodes (
  id uuid primary key default gen_random_uuid(),
  token text not null unique,
  title text not null default 'Оценка характеристик',
  status text not null default 'open' check (status in ('open', 'revealing', 'closed')),
  created_at timestamptz not null default now(),
  closed_at timestamptz
);

create table if not exists public.rating_episode_votes (
  id bigint generated by default as identity primary key,
  episode_id uuid not null references public.rating_episodes(id) on delete cascade,
  voter_player_id bigint not null references public.players(id) on delete cascade,
  rated_player_id bigint not null references public.players(id) on delete cascade,
  attribute_key text not null,
  score smallint not null check (score >= 1 and score <= 10),
  created_at timestamptz not null default now(),
  unique (episode_id, voter_player_id, rated_player_id, attribute_key)
);

create index if not exists rating_episode_votes_episode_idx
  on public.rating_episode_votes (episode_id);

create table if not exists public.player_attributes (
  player_id bigint primary key references public.players(id) on delete cascade,
  attrs jsonb not null default '{}'::jsonb,
  episode_id uuid references public.rating_episodes(id) on delete set null,
  updated_at timestamptz not null default now()
);

alter table public.rating_episodes enable row level security;
alter table public.rating_episode_votes enable row level security;
alter table public.player_attributes enable row level security;

grant select on public.rating_episodes to anon, authenticated;
grant select, insert, update, delete on public.rating_episodes to authenticated;
grant select on public.rating_episode_votes to anon, authenticated;
grant select, insert, update, delete on public.rating_episode_votes to authenticated;
grant select on public.player_attributes to anon, authenticated;
grant select, insert, update, delete on public.player_attributes to authenticated;

drop policy if exists "rating_episodes_select" on public.rating_episodes;
create policy "rating_episodes_select"
  on public.rating_episodes for select to anon, authenticated using (true);

drop policy if exists "rating_episodes_admin_all" on public.rating_episodes;
create policy "rating_episodes_admin_all"
  on public.rating_episodes for all to authenticated
  using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  )
  with check (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

drop policy if exists "rating_episode_votes_select" on public.rating_episode_votes;
create policy "rating_episode_votes_select"
  on public.rating_episode_votes for select to anon, authenticated using (true);

drop policy if exists "rating_episode_votes_insert" on public.rating_episode_votes;
create policy "rating_episode_votes_insert"
  on public.rating_episode_votes for insert to authenticated with check (true);

drop policy if exists "rating_episode_votes_update" on public.rating_episode_votes;
create policy "rating_episode_votes_update"
  on public.rating_episode_votes for update to authenticated using (true) with check (true);

drop policy if exists "rating_episode_votes_delete" on public.rating_episode_votes;
create policy "rating_episode_votes_delete"
  on public.rating_episode_votes for delete to authenticated using (true);

drop policy if exists "player_attributes_select" on public.player_attributes;
create policy "player_attributes_select"
  on public.player_attributes for select to anon, authenticated using (true);

drop policy if exists "player_attributes_write" on public.player_attributes;
create policy "player_attributes_write"
  on public.player_attributes for all to authenticated using (true) with check (true);
