-- Фаза «результаты» перед публикацией рейтинга
-- Supabase → SQL Editor → Run (после rating_episode.sql)

alter table public.rating_episodes
  drop constraint if exists rating_episodes_status_check;

alter table public.rating_episodes
  add constraint rating_episodes_status_check
  check (status in ('open', 'revealing', 'closed'));

create table if not exists public.rating_episode_acknowledgments (
  id bigint generated by default as identity primary key,
  episode_id uuid not null references public.rating_episodes(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  acknowledged_at timestamptz not null default now(),
  unique (episode_id, player_id)
);

create index if not exists rating_episode_ack_episode_idx
  on public.rating_episode_acknowledgments (episode_id);

alter table public.rating_episode_acknowledgments enable row level security;

grant select on public.rating_episode_acknowledgments to anon, authenticated;
grant select, insert, update, delete on public.rating_episode_acknowledgments to authenticated;

drop policy if exists "rating_episode_ack_select" on public.rating_episode_acknowledgments;
create policy "rating_episode_ack_select"
  on public.rating_episode_acknowledgments for select to anon, authenticated using (true);

drop policy if exists "rating_episode_ack_insert" on public.rating_episode_acknowledgments;
create policy "rating_episode_ack_insert"
  on public.rating_episode_acknowledgments for insert to authenticated with check (true);

drop policy if exists "rating_episode_ack_delete" on public.rating_episode_acknowledgments;
create policy "rating_episode_ack_delete"
  on public.rating_episode_acknowledgments for delete to authenticated using (true);

-- Обновить эпизод, который уже закрыт автоматически, но рейтинг ещё не опубликован вручную — при необходимости вручную:
-- update rating_episodes set status = 'revealing' where status = 'closed' and closed_at is null;
