-- Участие в тренировке: игрок сам отмечает «Не был» / «Не буду голосовать»
-- Запустите в Supabase → SQL Editor, затем training_participation_rls.sql

create table if not exists public.training_player_participation (
  id bigint generated by default as identity primary key,
  training_id bigint not null references public.training_sessions(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  participated boolean not null default true,
  skipped_rating_vote boolean not null default false,
  unique (training_id, player_id)
);

create index if not exists training_player_participation_training_id_idx
  on public.training_player_participation (training_id);

alter table public.training_player_participation enable row level security;

grant select on public.training_player_participation to anon, authenticated;
grant select, insert, update, delete on public.training_player_participation to authenticated;

drop policy if exists "training_player_participation_select" on public.training_player_participation;
create policy "training_player_participation_select"
  on public.training_player_participation for select to anon, authenticated using (true);

-- Политики записи (только своя строка) — в training_participation_rls.sql
