-- Тренировки и оценки после них (меньший бонус к ★, чем после матча)
-- Запустите в Supabase → SQL Editor

create table if not exists public.training_sessions (
  id bigint generated by default as identity primary key,
  title text not null,
  date text not null,
  time text not null default '19:00',
  location text,
  notes text,
  is_completed boolean not null default false,
  rating_voting_ends_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists training_sessions_date_idx
  on public.training_sessions (date desc, id desc);

create table if not exists public.training_rating_votes (
  id bigint generated by default as identity primary key,
  training_id bigint not null references public.training_sessions(id) on delete cascade,
  voter_player_id bigint not null references public.players(id) on delete cascade,
  rated_player_id bigint not null references public.players(id) on delete cascade,
  stars integer not null check (stars >= 1 and stars <= 10),
  created_at timestamptz default now(),
  unique (training_id, voter_player_id, rated_player_id)
);

create index if not exists training_rating_votes_training_id_idx
  on public.training_rating_votes (training_id);

create table if not exists public.training_rating_summary (
  id bigint generated by default as identity primary key,
  training_id bigint not null references public.training_sessions(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  avg_stars numeric(4, 2) not null default 0,
  training_rating numeric(3, 1) not null default 0,
  vote_count integer not null default 0,
  rating_before numeric(4, 1),
  rating_after numeric(4, 1),
  unique (training_id, player_id)
);

create index if not exists training_rating_summary_training_id_idx
  on public.training_rating_summary (training_id);

alter table public.training_sessions enable row level security;
alter table public.training_rating_votes enable row level security;
alter table public.training_rating_summary enable row level security;

grant select on public.training_sessions to anon, authenticated;
grant select, insert, update, delete on public.training_sessions to authenticated;

grant select on public.training_rating_votes to anon, authenticated;
grant select, insert, update, delete on public.training_rating_votes to authenticated;

grant select on public.training_rating_summary to anon, authenticated;
grant select, insert, update, delete on public.training_rating_summary to authenticated;

drop policy if exists "training_sessions_select" on public.training_sessions;
create policy "training_sessions_select"
  on public.training_sessions for select to anon, authenticated using (true);

drop policy if exists "training_sessions_write" on public.training_sessions;
create policy "training_sessions_write"
  on public.training_sessions for all to authenticated using (true) with check (true);

drop policy if exists "training_rating_votes_select" on public.training_rating_votes;
create policy "training_rating_votes_select"
  on public.training_rating_votes for select to anon, authenticated using (true);

drop policy if exists "training_rating_votes_write" on public.training_rating_votes;
create policy "training_rating_votes_write"
  on public.training_rating_votes for all to authenticated using (true) with check (true);

drop policy if exists "training_rating_summary_select" on public.training_rating_summary;
create policy "training_rating_summary_select"
  on public.training_rating_summary for select to anon, authenticated using (true);

drop policy if exists "training_rating_summary_write" on public.training_rating_summary;
create policy "training_rating_summary_write"
  on public.training_rating_summary for all to authenticated using (true) with check (true);
