-- LOCAL DEV mirror of supabase/match_gamification.sql (canonical hosted file).
-- Applied by `supabase start` / `supabase db reset` so the gamification tables
-- exist locally. Keep in sync with supabase/match_gamification.sql.

create table if not exists public.player_achievements (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  achievement_key text not null,
  match_id bigint references public.matches(id) on delete set null,
  earned_at timestamptz not null default now(),
  unique (player_id, achievement_key)
);
create index if not exists player_achievements_player_id_idx on public.player_achievements (player_id);

create table if not exists public.player_career (
  player_id bigint primary key references public.players(id) on delete cascade,
  xp integer not null default 0,
  level integer not null default 1,
  title text not null default 'Новичок',
  matches_rated integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.player_season_stats (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  season integer not null,
  matches_rated integer not null default 0,
  sum_rating numeric(8, 2) not null default 0,
  avg_rating numeric(4, 2) not null default 0,
  updated_at timestamptz not null default now(),
  unique (player_id, season)
);
create index if not exists player_season_stats_player_id_idx on public.player_season_stats (player_id);

alter table public.player_achievements enable row level security;
alter table public.player_career enable row level security;
alter table public.player_season_stats enable row level security;

grant select on public.player_achievements, public.player_career, public.player_season_stats to anon, authenticated;
grant all on public.player_achievements, public.player_career, public.player_season_stats to service_role;
grant usage, select on all sequences in schema public to service_role;

create policy player_achievements_select on public.player_achievements for select to anon, authenticated using (true);
create policy player_career_select on public.player_career for select to anon, authenticated using (true);
create policy player_season_stats_select on public.player_season_stats for select to anon, authenticated using (true);
